# Generated by Django 4.2.1 on 2023-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(max_length=50, null=True)),
                ('mobile', models.ImageField(max_length=50, null=True, upload_to='')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='user_img')),
            ],
        ),
    ]
