# Generated by Django 4.2.1 on 2023-09-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0002_alter_regdb_mobile_alter_regdb_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdb',
            name='location',
        ),
        migrations.RemoveField(
            model_name='regdb',
            name='pincode',
        ),
    ]
