# Generated by Django 4.2.1 on 2023-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0003_remove_regdb_location_remove_regdb_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_cata', models.CharField(blank=True, max_length=50, null=True)),
                ('P_name', models.CharField(blank=True, max_length=50, null=True)),
                ('P_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('P_number', models.IntegerField(blank=True, null=True)),
                ('P_location', models.CharField(blank=True, max_length=500, null=True)),
                ('P_price', models.IntegerField(blank=True, null=True)),
                ('P_description', models.CharField(blank=True, max_length=500, null=True)),
                ('P_image1', models.ImageField(blank=True, null=True, upload_to='B_product')),
                ('P_image2', models.ImageField(blank=True, null=True, upload_to='B_product')),
                ('P_image3', models.ImageField(blank=True, null=True, upload_to='B_product')),
            ],
        ),
    ]
