# Generated by Django 4.2.1 on 2023-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='sam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_image1', models.ImageField(blank=True, null=True, upload_to='B_product')),
                ('P_image2', models.ImageField(blank=True, null=True, upload_to='B_product')),
                ('P_image3', models.ImageField(blank=True, null=True, upload_to='B_product')),
            ],
        ),
    ]
