# Generated by Django 4.2.1 on 2023-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0006_alter_sam_p_image1_alter_sam_p_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_sdescription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
