# Generated by Django 4.2.1 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0007_product_p_sdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
