# Generated by Django 4.2.1 on 2023-09-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front1', '0008_product_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_localarea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='P_shopname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
