# Generated by Django 4.2.1 on 2023-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_categoryname', models.CharField(blank=True, max_length=50, null=True)),
                ('A_description', models.CharField(blank=True, max_length=500, null=True)),
                ('A_image', models.ImageField(upload_to='category')),
            ],
        ),
    ]
