# Generated by Django 4.2.1 on 2023-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_categoryname', models.CharField(blank=True, max_length=50, null=True)),
                ('C_description', models.CharField(blank=True, max_length=500, null=True)),
                ('D_image', models.ImageField(upload_to='category')),
            ],
        ),
    ]
