# Generated by Django 4.2.1 on 2023-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_categoryb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorya',
            name='A_image',
            field=models.ImageField(upload_to='A_category'),
        ),
    ]
