# Generated by Django 4.2.1 on 2023-08-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_categorya_a_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorya',
            name='A_image',
            field=models.ImageField(blank=True, null=True, upload_to='A_category'),
        ),
        migrations.AlterField(
            model_name='categoryb',
            name='D_image',
            field=models.ImageField(blank=True, null=True, upload_to='B_category'),
        ),
    ]
