# Generated by Django 4.2.1 on 2023-09-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_categorya_a_image_alter_categoryb_d_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryB',
        ),
    ]
